name: Run GHCN download code 
on: 
  workflow_dispatch:
  schedule:
    - cron: '20 11 * * *'

jobs:
  runcode:
    runs-on: ubuntu-latest
    steps:
      - name: Run  
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USER}}
          key: ${{secrets.SSH_KEY}}
          command_timeout: 90m
          script: |
              cd /g/data/ia39/aus-ref-clim-data-nci/ghcn/code
              ./ghcn.sh
              #git add update_log.txt
              #git commit -m 'updated log'
              #git push origin
